insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Al Dhabi Building');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Al Fardan Building');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Al Odaid Office Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Al Taghreed Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Fotouh Al Khair');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Owaida Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Rawda Building');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Airport Road','Airport Road','Sheikh Nahyan Bin Zayed Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Badaa','Al Badaa','Al Badaa');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bahia','Al Bahia','Al Bahia');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Bateen','Al Bateen Airport');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Bateen','Al Bateen Villas');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Bateen Wharf','Marasy');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Ettihad Towers','Al Ettihad Tower 1');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Ettihad Towers','Al Ettihad Tower 2');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Ettihad Towers','Al Ettihad Tower 3');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Ettihad Towers','Al Ettihad Tower 4');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Ettihad Towers','Al Ettihad Tower 5');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Khaleej Al Arabi Street','Al Bateen Park');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Khaleej Al Arabi Street','Al Gurm Centre');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Khaleej Al Arabi Street','Al Khaleej Al Arabi Street');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Khaleej Al Arabi Street','Capital Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Bateen','Al Khaleej Al Arabi Street','NBAD Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Dhafrah','Al Dhafrah 1','Al Dhafrah 1');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Dhafrah','Al Dhafrah 2','Al Dhafrah 2');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Falah City','Al Falah City','Al Falah City');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Al Baraha Village','Al Baraha Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Al Buhayra Village','Al Buhayra Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Al Khaleej Village','Al Khaleej Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Al Khubaira Village','Al Khubaira Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Falaj Village','Falaj Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Liwa Village','Liwa Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ghadeer','Liwa Village','Liwa Village Villas');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Hudayriat Island','North Hudayriat','North Hudayriat');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Hudayriat Island','South Hudayriat','South Hudayriat');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Ittihad Road','Al Ittihad Road','Al Ittihad Road');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Karama','Al Karama','Al Karama');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Karama','Al Maharba','Al Maharba');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Karama','Al Musalla Area','Liwa Village');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Istiqlal Street','Al Istiqlal Street');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Istiqlal Street','Raha Building');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Istiqlal Street','X Panasonic Showroom');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','20 Villas Project');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Ahlia tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Hana Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Khubairah Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Nakheel Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Ras Al Akhdar');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Sawari Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Al Waha Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Amwaj Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','First Gulf Bank Building');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Hilton Baynouna');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Kamala Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Khalidiya Palace Rayhaan');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','Park Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Abu Dhabi','Al Khalidiya','Al Khalidiya','The Crystal Tower');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Al Ain','Al Hili','Al Hilli','Hili Rayhaan by Rotana');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 3','Block 3');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 5','Block 5');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 6','Block 6');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 7','Block 7');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 8','Block 8');
insert into tb_propertyfinder (city, community, subcommunity, re_property) values('Dubai','Academic City','Block 9','Block 9');