insert into tb_community (id,city_id, community_name) values('40','1','Al Wahda');
insert into tb_community (id,city_id, community_name) values('41','1','Al Wathba');
insert into tb_community (id,city_id, community_name) values('42','1','Al Zaab');
insert into tb_community (id,city_id, community_name) values('43','1','Baniyas');
insert into tb_community (id,city_id, community_name) values('44','1','Between Two Bridges');
insert into tb_community (id,city_id, community_name) values('45','1','Building Materials City');
insert into tb_community (id,city_id, community_name) values('46','1','Capital Centre');
insert into tb_community (id,city_id, community_name) values('47','1','City Downtown');
insert into tb_community (id,city_id, community_name) values('48','1','Corniche Area');
insert into tb_community (id,city_id, community_name) values('49','1','Corniche Road');
insert into tb_community (id,city_id, community_name) values('50','1','Danet Abu Dhabi');
insert into tb_community (id,city_id, community_name) values('51','1','Defence Street');
insert into tb_community (id,city_id, community_name) values('52','1','Desert Village');
insert into tb_community (id,city_id, community_name) values('53','1','Eastern Road');
insert into tb_community (id,city_id, community_name) values('54','1','Electra Street');
insert into tb_community (id,city_id, community_name) values('55','1','Ghantoot');
insert into tb_community (id,city_id, community_name) values('56','1','Grand Mosque District');
insert into tb_community (id,city_id, community_name) values('57','1','Hamdan Street');
insert into tb_community (id,city_id, community_name) values('58','1','Hameem');
insert into tb_community (id,city_id, community_name) values('59','1','Hydra Village');
insert into tb_community (id,city_id, community_name) values('60','1','Jawazat Street');
insert into tb_community (id,city_id, community_name) values('61','1','Khalifa City');
insert into tb_community (id,city_id, community_name) values('62','1','Khalifa Street');
insert into tb_community (id,city_id, community_name) values('63','1','Liwa');
insert into tb_community (id,city_id, community_name) values('64','1','Lulu Island');
insert into tb_community (id,city_id, community_name) values('65','1','Madinat Zayed');
insert into tb_community (id,city_id, community_name) values('66','1','Marina Village');
insert into tb_community (id,city_id, community_name) values('67','1','Masdar City');
insert into tb_community (id,city_id, community_name) values('68','1','Mohamed Bin Zayed City');
insert into tb_community (id,city_id, community_name) values('69','1','Muroor Area');
insert into tb_community (id,city_id, community_name) values('70','1','Mussafah');
insert into tb_community (id,city_id, community_name) values('71','1','Nurai Island');
insert into tb_community (id,city_id, community_name) values('72','1','Saadiyat Island');
insert into tb_community (id,city_id, community_name) values('73','1','Sas Al Nakheel');
insert into tb_community (id,city_id, community_name) values('74','1','Tourist Club Area');
insert into tb_community (id,city_id, community_name) values('75','1','Umm Al Nar');
insert into tb_community (id,city_id, community_name) values('76','1','Yas Island');
insert into tb_community (id,city_id, community_name) values('77','1','Zayed Military City');
insert into tb_community (id,city_id, community_name) values('78','1','Zayed Sports City');
insert into tb_community (id,city_id, community_name) values('79','2','Ain Ajman');
insert into tb_community (id,city_id, community_name) values('80','2','Ajman Corniche Road');
insert into tb_community (id,city_id, community_name) values('81','2','Ajman Downtown');
insert into tb_community (id,city_id, community_name) values('82','2','Ajman Industrial Area');
insert into tb_community (id,city_id, community_name) values('83','2','Ajman Meadows');
insert into tb_community (id,city_id, community_name) values('84','2','Ajman Uptown');
insert into tb_community (id,city_id, community_name) values('85','2','Al Ameera Village');
insert into tb_community (id,city_id, community_name) values('86','2','Al Bustan');
insert into tb_community (id,city_id, community_name) values('87','2','Al Humaid City');
insert into tb_community (id,city_id, community_name) values('88','2','Al Ittihad Village');
insert into tb_community (id,city_id, community_name) values('89','2','Al Mueihat');
insert into tb_community (id,city_id, community_name) values('90','2','Al Naemiyah');
insert into tb_community (id,city_id, community_name) values('91','2','Al Rashidiya');
insert into tb_community (id,city_id, community_name) values('92','2','Al Rumaila');
insert into tb_community (id,city_id, community_name) values('93','2','Al Sawan');
insert into tb_community (id,city_id, community_name) values('94','2','Al Zahraa');
insert into tb_community (id,city_id, community_name) values('95','2','Al Zorah');
insert into tb_community (id,city_id, community_name) values('96','2','Awali City');
insert into tb_community (id,city_id, community_name) values('97','2','Corniche Ajman');
insert into tb_community (id,city_id, community_name) values('98','2','Emirates City');
insert into tb_community (id,city_id, community_name) values('99','2','Garden City');
insert into tb_community (id,city_id, community_name) values('100','2','Green City');
insert into tb_community (id,city_id, community_name) values('101','2','Manama');
insert into tb_community (id,city_id, community_name) values('102','2','Marmooka City');
insert into tb_community (id,city_id, community_name) values('103','2','Masfoot');
insert into tb_community (id,city_id, community_name) values('104','2','Musheiref');
insert into tb_community (id,city_id, community_name) values('105','2','New industrial area');
insert into tb_community (id,city_id, community_name) values('106','2','Park View City');
insert into tb_community (id,city_id, community_name) values('107','2','Sheikh Khalifa Bin Zayed Street');
insert into tb_community (id,city_id, community_name) values('108','3','Al Ain Industrial Area');
insert into tb_community (id,city_id, community_name) values('109','3','Al Buraymi');
insert into tb_community (id,city_id, community_name) values('110','3','Al Faqa\'a');
insert into tb_community (id,city_id, community_name) values('111','3','Al Hili');
insert into tb_community (id,city_id, community_name) values('112','3','Al Jaheli');
insert into tb_community (id,city_id, community_name) values('113','3','Al Jimi');
insert into tb_community (id,city_id, community_name) values('114','3','Al Khabisi');
insert into tb_community (id,city_id, community_name) values('115','3','Al Manaseer');
insert into tb_community (id,city_id, community_name) values('116','3','Al Maqam');
insert into tb_community (id,city_id, community_name) values('117','3','Al Markhaniya');
insert into tb_community (id,city_id, community_name) values('118','3','Al Mutarad');
insert into tb_community (id,city_id, community_name) values('119','3','Al Oyoun Village');
insert into tb_community (id,city_id, community_name) values('120','3','Al Sinaiya');
insert into tb_community (id,city_id, community_name) values('121','3','Al Tawiya');
insert into tb_community (id,city_id, community_name) values('122','3','Tawam');
insert into tb_community (id,city_id, community_name) values('123','3','Zakher');
insert into tb_community (id,city_id, community_name) values('124','4','Academic City');
insert into tb_community (id,city_id, community_name) values('125','4','Al Aweer');
insert into tb_community (id,city_id, community_name) values('126','4','Al Bada\'a');
insert into tb_community (id,city_id, community_name) values('127','4','Al Barari');
insert into tb_community (id,city_id, community_name) values('128','4','Al Barsha');
insert into tb_community (id,city_id, community_name) values('129','4','Al Furjan');
insert into tb_community (id,city_id, community_name) values('130','4','Al Garhoud');
insert into tb_community (id,city_id, community_name) values('131','4','Al Hamriya');
insert into tb_community (id,city_id, community_name) values('132','4','Al Jafiliya');

insert into tb_community (id,city_id, community_name) values('133','4','Al Karama');
insert into tb_community (id,city_id, community_name) values('134','4','Al Khawaneej');

insert into tb_community (id,city_id, community_name) values('135','4','Al Mizhar');
insert into tb_community (id,city_id, community_name) values('136','4','Al Muhaisnah');
insert into tb_community (id,city_id, community_name) values('137','4','Al Nahda Dubai');
insert into tb_community (id,city_id, community_name) values('138','4','Al Qasba\'a');
insert into tb_community (id,city_id, community_name) values('139','4','Al Qusais');
insert into tb_community (id,city_id, community_name) values('140','4','Al Rashidiya');


