insert into tb_subcommunity (id, community_id, subcommunity_name) values('21','10','North Hudayriat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('22','10','South Hudayriat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('23','11','Al Ittihad Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('24','12','Al Karama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('25','12','Al Maharba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('26','12','Al Musalla Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('27','13','Al Hosn');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('28','13','Al Istiqlal Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('29','13','Al Khalidiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('30','13','Cornich Al Khalidiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('31','13','Crescent Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('32','13','Khalidiya Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('33','13','Khalidiya Twin Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('34','13','Khalidiya Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('35','14','Al Maffraq');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('36','15','Al Manaseer');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('37','16','Al Manhal');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('38','18','Al Maqtaa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('39','18','Hills Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('40','19','Al Markaziyah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('41','20','Maryah Plaza');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('42','20','Sowwah Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('43','21','Al Mina');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('44','22','Al Maha Complex');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('45','22','Al Yasat Compound');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('46','22','Delma Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('47','22','Mushrif Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('48','22','Mushrif Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('49','22','Palm Oasis');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('50','23','Al Nahda Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('51','24','Al Nahyan Camp');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('52','25','Al Najda Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('53','26','Al Qurm Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('54','26','Al Qurm Resort');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('55','26','Al Qurm Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('56','26','Corniche Al Qurm');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('57','27','Al Bandar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('58','27','Al Dana');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('59','27','Al Lissaily');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('60','27','Al Muneera');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('61','27','Al Razeen');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('62','27','Al Rumaila');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('63','27','Al Seef');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('64','27','Al Shaleela');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('65','27','Al Thurayya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('66','27','Al Zahiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('67','27','Al Zeina');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('68','27','Khor Al Raha');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('69','27','Mira Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('70','28','Al Raha Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('71','29','Al Raha Golf Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('72','30','Al Rahba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('73','31','Al Rawdah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('74','32','Al Reef Downtown');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('75','32','Al Reef Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('76','33','Al Reem Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('77','33','City Of Lights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('78','33','Marina Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('79','33','Najmat Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('80','33','Shams Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('81','33','Shams Gate District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('82','35','Al Salam Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('83','35','Bloom Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('84','36','Al Samha');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('85','36','Khalifa Industrial Zone Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('86','37','Al Shahama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('87','37','New Shahama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('88','38','Al Shamkha');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('89','39','Al Shawamekh');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('90','40','Al Wahda');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('91','40','Al Wahda City Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('92','40','Al Wahda Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('93','41','Al Wathba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('94','42','Al Zaab');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('95','43','Baniyas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('96','44','Between Two Bridges');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('97','45','Building Materials City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('98','45','Commercial District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('99','45','Residential District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('100','46','Capital Centre');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('101','47','Al Falah Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('102','47','CBD (Central Business District)');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('103','47','Defense Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('104','48','Burj Mohammed Bin Rashid at WTC');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('105','48','Cornich Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('106','48','Saraya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('107','49','AL Diar Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('108','49','Al Sahel Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('109','49','Corniche Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('110','49','Etihad Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('111','49','Nation Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('112','49','Saraya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('113','50','Danet Abu Dhabi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('114','51','Defence Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('115','52','Desert Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('116','53','Al Muzoon District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('117','53','Al Reehan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('118','53','East Corniche road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('119','53','Eastern Mangroves Complex');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('120','53','Khalifa Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('121','54','Electra Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('122','56','Desert Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('123','56','Rihan Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('124','57','East Corniche road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('125','57','Hamdan Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('126','57','Liwa Centre Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('127','58','Hameem Residential City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('128','59','Hydra Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('129','60','Jawazat Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('130','61','Khalifa City A');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('131','61','Khalifa City B');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('132','61','Khalifa City C');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('133','62','Khalifa Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('134','62','Lulu Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('135','63','Liwa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('136','64','Lulu Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('137','65','Madinat Zayed');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('138','66','Marina Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('139','67','Madinat Zayed');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('140','67','Masdar City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('141','68','Desert Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('142','68','Mohamed Bin Zayed City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('143','68','Prestige Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('144','69','Al Mamoura');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('145','69','Hadbat Al Zafranah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('146','69','Muroor Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('147','69','Muroor Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('148','70','Mussafah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('149','70','Mussafah Industrial Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('150','71','Beachfront Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('151','71','Nurai Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('152','72','Al Saadiyat Avenue');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('153','72','Marina Al Saadiyat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('154','72','Saadiyat Beach');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('155','72','Saadiyat Cultural District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('156','72','Saadiyat Lagoons');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('157','72','Saadiyat Promenade');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('158','72','Saadiyat Resort');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('159','73','Abu Dhabi Golf Club');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('160','73','Sas Al Nakheel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('161','73','Sas Al Nakheel Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('162','74','Mina Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('163','74','Tourist Club Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('164','75','Umm Al Nar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('165','76','Yas Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('166','77','Zayed Military City Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('167','78','Zayed Sports City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('168','79','Ain Ajman');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('169','80','Ajman Corniche Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('170','81','Ajman Downtown');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('171','81','Ajman Pearl Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('172','81','Al Jurf');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('173','81','Al Khail Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('174','81','Al Khor Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('175','81','Al Nakheel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('176','81','Al Rashidiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('177','81','Al Rashidiya Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('178','81','Falcon Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('179','81','Horizon Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('180','81','Times Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('181','82','Ajman Industrial 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('182','82','Ajman Industrial 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('183','84','Ajman Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('184','84','Ajman One');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('185','84','Ajman Uptown Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('186','84','Al Hleio');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('187','85','Al Ameera Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('188','86','Al Bustan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('189','86','Orient Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('190','87','Al Humaid City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('191','87','Al Rashid Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('192','87','Blossom Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('193','87','Highfield Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('194','87','Savannah Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('195','88','Al Ittihad Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('196','89','Al Mueihat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('197','90','Al Naemiya Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('198','90','Al Naimiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('199','91','Al Rashidiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('200','92','Al Rumaila');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('201','93','Ajman One Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('202','93','Al Sawan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('203','94','Al Zahraa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('204','95','Beachfront');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('205','95','Creekside');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('206','95','Gateway');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('207','95','Golf Community');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('208','95','Peninsula');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('209','96','Awali City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('210','97','Corniche Ajman');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('211','98','Emirates City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('212','98','Emirates Lake Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('213','98','Emirates Pearls');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('214','98','Goldcrest Dreams');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('215','98','Green Lake Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('216','98','Lake View Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('217','98','Paradise Lakes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('218','98','Rainbow Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('219','98','Shami Twin Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('220','99','Garden City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('221','99','Jasmine Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('222','99','Mandarin Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('223','100','Green City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('224','101','Manama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('225','102','Marmooka City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('226','102','Shami Garden Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('228','105','New industrial area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('229','106','Century Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('230','106','ICT Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('231','106','Park View City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('232','107','Sheikh Khalifa Bin Zayed Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('233','111','Al Hilli');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('234','111','Beda Bint Soud');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('235','112','Al Jaheli');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('236','15','Al Manaseer');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('237','117','Green Land Compound');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('238','118','Al Mutarad');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('239','119','Al Oyoun Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('240','120','Al Sinaiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('241','123','Shaab Al Askar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('242','124','Block 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('243','124','Block 5');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('244','124','Block 6');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('245','124','Block 7');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('246','124','Block 8');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('247','124','Block 9');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('248','125','Al Aweer Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('249','125','warsan estate');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('250','126','Al Bada\'a');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('251','127','Al Barari Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('252','127','Ashjar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('253','127','Seventh Heaven');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('254','127','The Reserve');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('255','127','wadi al safa');
Insert into tb_subcommunity (id, community_id, subcommunity_name) values('256','128','Al Barsha 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('257','128','Al Barsha 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('258','128','Al Barsha 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('259','128','Al Barsha South');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('260','128','Montrose');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('261','128','Villa Lantana');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('262','129','Avenue Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('263','129','Azizi Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('264','129','East Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('265','129','North Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('266','129','Phase 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('267','129','Phase 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('268','129','Phase 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('269','129','South Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('270','129','The Dreamz');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('271','129','Village Center');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('272','129','West Village');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('275','131','Al Hamriya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('276','131','Al Wuheida');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('277','124','Block 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('278','124','Block 5');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('279','124','Block 6');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('280','124','Block 7');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('281','124','Block 8');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('282','124','Block 9');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('283','132','Al Jafiliya');


insert into tb_subcommunity (id, community_id, subcommunity_name) values('284','133','Al Karama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('285','133','Karama Park Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('286','133','Shaikh Hamdan Colony');


insert into tb_subcommunity (id, community_id, subcommunity_name) values('287','134','Al Khawaneej 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('288','134','Al Khawaneej 2');


insert into tb_subcommunity (id, community_id, subcommunity_name) values('289','135','Al Mizhar 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('290','135','Al Mizhar 2');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('291','136','Al Muhaisnah 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('292','136','Al Muhaisnah 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('293','136','Al Muhaisnah 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('294','136','Al Muhaisnah 4');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('295','136','Sonapur');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('296','137','Al Nahda 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('297','137','Al Nahda 2');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('298','138','Al Qasba\a');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('299','139','Al Qusais');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('300','139','Al Qusais Industrial Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('301','139','Al Qusais Residential Area');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('302','140','Al Rashidiya');

insert into tb_subcommunity (id, community_id, subcommunity_name) values('304','141','Al Karama');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('305','141','Karama Park Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('306','141','Shaikh Hamdan Colony');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('308','142','Al Khawaneej 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('309','142','Al Khawaneej 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('311','136','Al Muhaisnah 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('312','136','Al Muhaisnah 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('313','136','Al Muhaisnah 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('314','136','Al Muhaisnah 4');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('315','136','Sonapur');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('317','137','Al Nahda 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('318','137','Al Nahda 2');
