insert into tb_community (id,city_id, community_name) values('141','4','Al Qasba\a');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('320','141','Al Qasba\a');insert into tb_subcommunity (id, community_id, subcommunity_name) values('323','139','Al Qusais');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('324','139','Al Qusais Industrial Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('325','139','Al Qusais Residential Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('327','140','Al Rashidiya');
insert into tb_community (id,city_id, community_name) values('141','4','Al Safa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('329','141','Al Safa 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('330','141','Al Safa 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('331','141','Al Safa 3');
insert into tb_community (id,city_id, community_name) values('142','4','Al Satwa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('333','142','Al Diyafah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('334','142','Al Hudaiba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('335','142','Satwa Road');
insert into tb_community (id,city_id, community_name) values('143','4','Al Shindagah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('337','143','Al Shindagah');
insert into tb_community (id,city_id, community_name) values('144','4','Al Sufouh');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('339','144','Acacia Avenues');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('340','144','Al Sufouh 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('341','144','Al Sufouh 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('342','144','Al Sufouh Road');
insert into tb_community (id,city_id, community_name) values('145','4','Al Twar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('344','145','Al Twar 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('345','145','Al Twar 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('346','145','Al Twar 3');
insert into tb_community (id,city_id, community_name) values('146','4','Al Warqa'a');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('348','146','Al Warqa'a 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('349','146','Al Warqa'a 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('350','146','Al Warqa'a 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('351','146','Al Warqa'a 4');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('352','146','Al Warqa'a 5');
insert into tb_community (id,city_id, community_name) values('147','4','Al Wasl');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('354','147','Al Manara ');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('355','147','Al Wasl Road');
insert into tb_community (id,city_id, community_name) values('148','4','Arabian Ranches');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('357','148','Al Mahra');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('358','148','Al Reem');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('359','148','Alma');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('360','148','Alvorada');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('361','148','Aseel Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('362','148','Casa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('363','148','Golf Homes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('364','148','Hattan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('365','148','La Avenida');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('366','148','Lila');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('367','148','Mirador');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('368','148','Mirador La Colección');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('369','148','Palma');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('370','148','Palmera');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('371','148','Polo Homes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('372','148','Rasha Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('373','148','Rosa Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('374','148','Saheel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('375','148','Samara');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('376','148','Savannah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('377','148','Terra Nova');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('378','148','Yasmin Villas');
insert into tb_community (id,city_id, community_name) values('149','4','Bur Dubai');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('380','149','Al Ghubaiba Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('381','149','Al Rafa'a');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('382','149','Al Souk Al Kabeer');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('383','149','Khalid Bin Al Waleed Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('384','149','Mankhool');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('385','149','Mankhool Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('386','149','Mina Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('387','149','Oud Metha');
insert into tb_community (id,city_id, community_name) values('150','4','Business Bay');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('389','150','Bay Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('390','150','Bristol Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('391','150','Business Bay');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('392','150','Capital Bay');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('393','150','Churchill Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('394','150','Damac Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('395','150','Emirates Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('396','150','Empire Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('397','150','Executive Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('398','150','Hydra Twin Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('399','150','Lotus');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('400','150','Niki Lauda Twin Tower');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('401','150','Signature Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('402','150','Sky Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('403','150','Sobha Ivory Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('404','150','Starhill Towers & Gallery');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('405','150','Tasameem Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('406','150','The Atria');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('407','150','The Oberoi Centre');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('408','150','Ubora Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('409','150','Westburry Square');
insert into tb_community (id,city_id, community_name) values('151','4','Culture Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('411','151','Culture Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('412','151','Manazel Al Khor');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('413','151','Santeview');
insert into tb_community (id,city_id, community_name) values('152','4','Deira');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('415','152','Abu Baker Al Siddique Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('416','152','Abu Hail');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('417','152','Al Baraha');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('418','152','Al Hamriya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('419','152','Al Khabisi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('420','152','Al Mamzar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('421','152','Al Muraqqabat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('422','152','Al Murar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('423','152','Al Muteena');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('424','152','Al Ras');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('425','152','Al Riqqa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('426','152','Baniyas Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('427','152','Baniyas Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('428','152','Corniche Deira');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('429','152','Deira Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('430','152','Emaar Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('431','152','Hor Al Anz');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('432','152','International Airport Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('433','152','Maktoum Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('434','152','Nad Shamma');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('435','152','Naif');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('436','152','Port Saeed');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('437','152','Riggat Al Buteen');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('438','152','Salah Al Din Street');
insert into tb_community (id,city_id, community_name) values('153','4','DIFC');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('440','153','Central Park Tower');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('441','153','Currency House');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('442','153','DIFC');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('443','153','DIFC Tower');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('444','153','Emirates Financial Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('445','153','Gate Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('446','153','Park Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('447','153','The Gate Precinct');
insert into tb_community (id,city_id, community_name) values('154','4','Discovery Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('449','154','Cactus');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('450','154','Contemporary Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('451','154','Ibn Battuta Gate');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('452','154','Mediterranean Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('453','154','Mesoamerican');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('454','154','Mogul Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('455','154','Terra Del Sol');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('456','154','Zen Cluster');
insert into tb_community (id,city_id, community_name) values('155','4','Downtown Dubai');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('458','155','29 Burj Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('459','155','BLVD Crescent');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('460','155','BLVD Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('461','155','Boulevard Central Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('462','155','Boulevard Plaza Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('463','155','Burj Khalifa Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('464','155','Burj Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('465','155','Burj Place');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('466','155','Burj Views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('467','155','Burj Vista');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('468','155','Claren Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('469','155','Downtown Dubai');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('470','155','Emaar Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('471','155','Mohammad Bin Rashid Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('472','155','Paramount Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('473','155','South Ridge');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('474','155','Standpoint Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('475','155','The Address Fountain views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('476','155','The Address Sky view Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('477','155','The Grand Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('478','155','The Lofts');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('479','155','The Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('480','155','The Sterling');
insert into tb_community (id,city_id, community_name) values('156','4','Downtown Jebel Ali');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('482','156','Celestial Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('483','156','Deyaar Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('484','156','Downtown Jebel Ali');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('485','156','Image Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('486','156','KPM Twin Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('487','156','Parkside Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('488','156','Schon residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('489','156','Sienna Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('490','156','Suburbia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('491','156','The Galleries');
insert into tb_community (id,city_id, community_name) values('157','4','Dubai Festival City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('493','157','Dubai Festival City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('494','157','Four Seasons');
insert into tb_community (id,city_id, community_name) values('158','4','Dubai Healthcare City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('496','158','Dubai Healthcare city');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('498','141','Al Qasbaa');
insert into tb_community (id,city_id, community_name) values('142','4','Dubai Industrial City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('500','142','Base Metal Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('501','142','Chemicals Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('502','142','Food and Beverage Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('503','142','Industrial Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('504','142','Machinery & Mechanical Equipment Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('505','142','Mineral Products Zone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('506','142','Sahara Living');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('507','142','Sahara Meadows');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('508','142','Transport & Equipment Zone');
insert into tb_community (id,city_id, community_name) values('143','4','Dubai Investment Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('510','143','Dubai Investment Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('511','143','Dubai Lagoon');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('512','143','Dunes Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('513','143','European Business Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('514','143','Ewan Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('515','143','Regent Business Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('516','143','Schon Business Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('517','143','The Royal Estates');
insert into tb_community (id,city_id, community_name) values('144','4','Dubai Land');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('519','144','Akoya By Damac');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('520','144','Akoya Oxygen');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('521','144','Al Ruwayyah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('522','144','Al Waha');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('523','144','Arjan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('524','144','Bawadi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('525','144','City of Arabia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('526','144','Dubai Land');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('527','144','Dubai Lifestyle City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('528','144','Dubai Residence Complex');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('529','144','Elite Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('530','144','Eye Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('531','144','Falcon City of Wonders');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('532','144','Golf City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('533','144','Layan Community');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('534','144','Living Legends');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('535','144','Liwan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('536','144','Majan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('537','144','Maysan Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('538','144','Mizin');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('539','144','Mudon');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('540','144','Pacific Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('541','144','Remraam');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('542','144','Sanali Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('543','144','Skycourt Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('544','144','The Sustainable City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('545','144','The Villa');
insert into tb_community (id,city_id, community_name) values('145','4','Dubai Marina');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('547','145','Al Atina');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('548','145','Al Majara');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('549','145','Al Marjan Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('550','145','Al Sahab');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('551','145','Bay Central');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('552','145','D.E.C Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('553','145','Dream Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('554','145','Dubai Marina');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('555','145','Dubai Marina Walk');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('556','145','Emaar 6 Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('557','145','Marina Diamonds');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('558','145','Marina Gate');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('559','145','Marina Promenade');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('560','145','Marina Quays');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('561','145','Marina View');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('562','145','Marina Wharf');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('563','145','Marinascape');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('564','145','Oceanic');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('565','145','Park Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('566','145','Silverene');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('567','145','Sparkle Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('568','145','The Jewels');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('569','145','The Waves');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('571','127','Al Barari Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('572','127','Ashjar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('573','127','Seventh Heaven');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('574','127','The Reserve');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('575','127','wadi al safa');
insert into tb_community (id,city_id, community_name) values('128','4','Dubai Pearl');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('577','128','Dubai Pearl');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('578','128','Dubai Pearl Hotel Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('579','128','Pearl Residences');
insert into tb_community (id,city_id, community_name) values('129','4','Dubai Promenade');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('581','129','Dubai Promenade');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('582','129','The Beach Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('583','129','The Channel Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('584','129','The Marina Towers');
insert into tb_community (id,city_id, community_name) values('130','4','Dubai Silicon Oasis');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('586','130','Atrium Gold Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('587','130','Axis Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('588','130','Coral Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('589','130','Donna Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('590','130','Dubai Silicon Oasis');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('591','130','Jade Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('592','130','Oasis High Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('593','130','Palace Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('594','130','Park Avenue');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('595','130','Ruby Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('596','130','Saima Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('597','130','Silicon Gates');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('598','130','Silicon Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('599','130','Spring Oasis');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('600','130','The Dunes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('601','130','The Platinum Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('602','130','University View');
insert into tb_community (id,city_id, community_name) values('131','4','Dubai Sports City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('604','131','Bloomingdale');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('605','131','Canal Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('606','131','Champions Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('607','131','Chapal The Destiny');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('608','131','Chapal The Glory');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('609','131','Crown Avenue');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('610','131','Dubai Sports City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('611','131','Eagle Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('612','131','Eden Garden');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('613','131','Elite Sports Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('614','131','Gallery Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('615','131','German Sports Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('616','131','Hub-Golf Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('617','131','Links View');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('618','131','Olympic Park Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('619','131','Park View');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('620','131','Prime villa');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('621','131','Royal Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('622','131','Rufy Residency');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('623','131','The Arena Apartments');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('624','131','Victory Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('625','131','Zenith Towers');
insert into tb_community (id,city_id, community_name) values('132','7','Al Naimiya Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('627','132','Al Naimiya Area');
insert into tb_community (id,city_id, community_name) values('133','4','Dubai Waterfront');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('629','133','Badrah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('630','133','Beachfront Living');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('631','133','Dubai Waterfront');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('632','133','Madinat Al Arab');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('633','133','Riviera');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('634','133','The Boulevard');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('635','133','The Waves');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('636','133','Uptown Waterfront');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('637','133','Veneto');
insert into tb_community (id,city_id, community_name) values('134','4','Dubai World Central');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('639','134','Amber Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('640','134','Business Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('641','134','Celestia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('642','134','Residential City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('643','134','Tenora');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('644','134','The Rubix');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('646','126','Al Bada'a');
insert into tb_community (id,city_id, community_name) values('127','4','Emirates Hills');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('648','127','Emirates Hills Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('649','127','Sector E');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('650','127','Sector H');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('651','127','Sector HT');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('652','127','Sector J');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('653','127','Sector L');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('654','127','Sector P');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('655','127','Sector R');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('656','127','Sector V');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('657','127','Sector W');
insert into tb_community (id,city_id, community_name) values('128','4','Forbidden City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('659','128','Ghawway');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('660','128','Hud Hud');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('661','128','Karawan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('662','128','Sallal');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('663','128','Tillali');
insert into tb_community (id,city_id, community_name) values('129','4','Global Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('665','129','Global Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('667','128','Al Barsha 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('668','128','Al Barsha 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('669','128','Al Barsha 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('670','128','Al Barsha South');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('671','128','Montrose');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('672','128','Villa Lantana');
insert into tb_community (id,city_id, community_name) values('129','4','Greens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('674','129','Al Alka');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('675','129','Al Arta');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('676','129','Al Dhafra');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('677','129','Al Ghaf');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('678','129','Al Ghozlan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('679','129','Al Jaz');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('680','129','Al Nakheel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('681','129','Al Samar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('682','129','Al Sidir');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('683','129','Al Thayyal');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('684','129','Greens');
insert into tb_community (id,city_id, community_name) values('130','4','IMPZ');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('686','130','Beirut Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('687','130','Centrium Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('688','130','Dana Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('689','130','IMPZ');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('690','130','Lago Vista');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('691','130','Lakeside Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('692','130','Oakwood Residency');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('693','130','Qasr Sabah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('694','130','Ramada Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('695','130','The Crescent');
insert into tb_community (id,city_id, community_name) values('131','4','International City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('697','131','Al Dana');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('698','131','CBD (Central Business District)');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('699','131','China Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('700','131','Emirates Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('701','131','England Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('702','131','France Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('703','131','Greece Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('704','131','Indigo Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('705','131','International City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('706','131','Italy Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('707','131','Lake District');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('708','131','Morocco Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('709','131','Persia Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('710','131','Phase 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('711','131','Prime Residency');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('712','131','Riviera Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('713','131','Russia Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('714','131','Spain Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('715','131','warsan village');
insert into tb_community (id,city_id, community_name) values('132','4','Jebel Ali');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('717','132','Jebel Ali Airport');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('718','132','Jebel Ali Freezone');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('719','132','Jebel Ali Industrial');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('720','132','Jebel Ali Port');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('721','132','Jebel Ali Village');
insert into tb_community (id,city_id, community_name) values('133','4','Jumeirah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('723','133','Jumeira Beach Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('724','133','Jumeirah 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('725','133','Jumeirah 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('726','133','Jumeirah 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('727','133','Pearl Jumeirah');
insert into tb_community (id,city_id, community_name) values('134','4','Jumeirah Beach Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('729','134','Al Fattan Marine Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('730','134','Amwaj');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('731','134','Bahar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('732','134','Murjan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('733','134','Rimal');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('734','134','Sadaf');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('735','134','Shams');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('736','134','The Walk');
insert into tb_community (id,city_id, community_name) values('135','4','Jumeirah Golf Estates');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('738','135','Earth');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('739','135','Fire');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('740','135','Jumeirah Golf Estates');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('741','135','Water');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('742','135','Wind');
insert into tb_community (id,city_id, community_name) values('136','4','Jumeirah Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('744','136','Cluster A');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('745','136','Cluster B');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('746','136','Cluster C');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('747','136','Cluster D');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('748','136','Cluster E');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('749','136','Cluster F');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('750','136','Loft Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('751','136','The Frond');
insert into tb_community (id,city_id, community_name) values('137','4','Jumeirah Islands');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('753','137','Contemporary Cluster');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('754','137','European Clusters');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('755','137','Islamic Clusters');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('756','137','Mediterranean Clusters');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('757','137','Oasis Clusters');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('758','137','The Mansions');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('759','137','Tropical Clusters');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('761','129','Avenue Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('762','129','Azizi Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('763','129','East Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('764','129','North Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('765','129','Phase 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('766','129','Phase 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('767','129','Phase 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('768','129','South Village');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('769','129','The Dreamz');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('770','129','Village Center');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('771','129','West Village');
insert into tb_community (id,city_id, community_name) values('130','4','Jumeirah Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('773','130','Heritage');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('774','130','Legacy');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('775','130','Mediterranean');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('776','130','Regional');
insert into tb_community (id,city_id, community_name) values('131','4','Jumeirah Village Circle');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('778','131','Al Muhra');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('779','131','Cadi Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('780','131','Desert Rose');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('781','131','Diamond Arch');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('782','131','Diamond Views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('783','131','District 14');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('784','131','District 16');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('785','131','District 18');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('786','131','Eden Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('787','131','Emirates Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('788','131','Excellence Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('789','131','Gardenia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('790','131','Green Court');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('791','131','Hanover Square');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('792','131','Indigo Ville');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('793','131','Jehaan Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('794','131','Jouri Residence 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('795','131','Jouri Residence 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('796','131','Jouri Residence 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('797','131','Jouri Residence 4');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('798','131','Jouri Residence 5');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('799','131','Jouri Residence 6');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('800','131','Judi');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('801','131','Jumeirah Village Circle');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('802','131','La Riviera Estate');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('803','131','Las Casas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('804','131','Masaar Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('805','131','Metropolis Lofts');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('806','131','Mirabella');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('807','131','Mirage Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('808','131','Monte Carlo Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('809','131','Nakheel Townhouses');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('810','131','Noora Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('811','131','Pacific Wave Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('812','131','Plaza Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('813','131','Quattro');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('814','131','Reliance Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('815','131','Rufi Downtown');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('816','131','Seasons Community');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('817','131','Serena Residence');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('818','131','Serenity Lakes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('819','131','Shamal Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('820','131','The Lawns');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('821','131','Tuscan Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('822','131','Westar');
insert into tb_community (id,city_id, community_name) values('132','4','Jumeirah Village Triangle');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('824','132','Green Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('825','132','Jumeirah Village Triangle');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('826','132','Silver Stallion Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('827','132','The Imperial Residence');
insert into tb_community (id,city_id, community_name) values('133','4','Maritime City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('829','133','Harbour Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('830','133','Jumeirah Waterfront');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('831','133','The Maritime Centre');
insert into tb_community (id,city_id, community_name) values('134','4','Meadows');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('833','134','Meadows');
insert into tb_community (id,city_id, community_name) values('135','4','Meydan City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('835','135','Meydan Avenue');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('836','135','Meydan City');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('837','135','Millennium Estates');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('838','135','The Polo Residence');
insert into tb_community (id,city_id, community_name) values('136','4','Mina Al Arab');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('840','136','Precinct Towers');
insert into tb_community (id,city_id, community_name) values('137','4','Mirdif');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('842','137','Al Badiya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('843','137','Ghoroob');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('844','137','Shorouq');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('845','137','Uptown Mirdif');
insert into tb_community (id,city_id, community_name) values('138','7','Al Ettihad Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('847','138','Al Ettihad Street');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('849','130','Airport Road Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('850','130','Al Garhoud');
insert into tb_community (id,city_id, community_name) values('131','4','Mushrif Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('852','131','Mushrif Park');
insert into tb_community (id,city_id, community_name) values('132','4','Nadd Al Hammar');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('854','132','Nad Al Hammar');
insert into tb_community (id,city_id, community_name) values('133','4','Nadd Al Sheba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('856','133','Nad Al Sheba 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('857','133','Nad Al Sheba 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('858','133','Nad Al Sheba 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('859','133','Nad Al Sheba 4');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('860','133','Sobha City');
insert into tb_community (id,city_id, community_name) values('134','4','Old Town');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('862','134','Kamoon');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('863','134','Miska');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('864','134','Reehan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('865','134','The Old Town Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('866','134','Yansoon');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('867','134','Zaafaran');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('868','134','Zanzabeel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('870','141','Al Qasbaa');
insert into tb_community (id,city_id, community_name) values('142','4','Palm Jebel Ali');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('872','142','Garden Homes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('873','142','Palm Jebel Ali');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('874','142','Palm Springs');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('875','142','Signature Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('876','142','The Cove');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('877','142','Water Homes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('878','142','Waterfront');
insert into tb_community (id,city_id, community_name) values('143','4','Palm Jumeirah');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('880','143','Atlantis The Palm');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('881','143','Azure Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('882','143','Canal Cove Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('883','143','Club Vista Mare');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('884','143','Garden Homes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('885','143','Gateway Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('886','143','Golden Mile');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('887','143','Grandeur Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('888','143','Kingdom of Sheba');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('889','143','Marina Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('890','143','Oceana');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('891','143','Palm Views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('892','143','Palma Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('893','143','Shoreline Apartments');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('894','143','Signature Villas');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('895','143','The Crescent');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('896','143','The Fairmont Palm Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('897','143','The Palm Tower');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('898','143','Tiara Residences');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('899','143','Viceroy');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('900','143','Water Villas');
insert into tb_community (id,city_id, community_name) values('144','4','Ras Al Khor');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('902','144','Ras Al Khor');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('903','144','Ras Al Khor Industrial');
insert into tb_community (id,city_id, community_name) values('145','7','Al Naimiya Area');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('905','145','Al Naimiya Area');
insert into tb_community (id,city_id, community_name) values('146','4','Sheikh Zayed Road');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('907','146','Al Moosa Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('908','146','Al Rostomani Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('909','146','API Trio Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('910','146','Emaar Business Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('911','146','Emirates Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('912','146','Saeed Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('913','146','Sheikh Zayed Road');
insert into tb_community (id,city_id, community_name) values('147','4','Technology Park');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('915','147','Technology Park');
insert into tb_community (id,city_id, community_name) values('148','4','Tecom');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('917','148','Al Fahad Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('918','148','Al Noor Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('919','148','Al Shaiba Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('920','148','Al Thuraya Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('921','148','Art Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('922','148','Executive Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('923','148','Green View');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('924','148','Madison Residency');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('925','148','Media Rotana Hotel Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('926','148','Onyx Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('927','148','Sky Central Hotel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('928','148','Smart Heights');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('929','148','Tecom');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('930','148','Tecom Two Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('931','148','Tecom Villas Complex');
insert into tb_community (id,city_id, community_name) values('149','4','The Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('933','149','The Gardens');
insert into tb_community (id,city_id, community_name) values('150','7','Al Nujoom Islands');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('935','150','Al Nujoom Islands');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('936','150','Blue Bay');
insert into tb_community (id,city_id, community_name) values('151','4','The Lagoons');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('938','151','Dubai Creek Harbour at The Lagoons');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('939','151','Dubai Lagoons');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('940','151','Phase 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('941','151','Phase 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('942','151','Phase 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('943','151','Phase 4');
insert into tb_community (id,city_id, community_name) values('152','4','The Lakes');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('945','152','Deema');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('946','152','Forat');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('947','152','Ghadeer');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('948','152','Hattan');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('949','152','Maeen');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('950','152','Zulal');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('952','131','Al Hamriya');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('953','131','Al Wuheida');
insert into tb_community (id,city_id, community_name) values('132','4','The Views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('955','132','Arno');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('956','132','Golf Towers');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('957','132','Mosela');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('958','132','The Fairways');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('959','132','The Links');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('960','132','The Views');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('961','132','Travo');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('962','132','Turia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('963','132','Una');
insert into tb_community (id,city_id, community_name) values('133','4','The World Islands');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('965','133','Asia');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('966','133','Coral Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('967','133','Europe');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('968','133','Germany Island ');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('969','133','Jasmine Gardens');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('970','133','Lebanon Island');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('971','133','Oqyana');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('972','133','Perseus - Rostov Island');
insert into tb_community (id,city_id, community_name) values('134','4','Umm Al Sheif');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('974','134','Umm Al Sheif');
insert into tb_community (id,city_id, community_name) values('135','4','Umm Hurair');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('976','135','Umm Hurair 1');
insert into tb_community (id,city_id, community_name) values('136','4','Umm Ramool');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('978','136','Umm Ramool');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('980','124','Block 3');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('981','124','Block 5');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('982','124','Block 6');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('983','124','Block 7');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('984','124','Block 8');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('985','124','Block 9');
insert into tb_community (id,city_id, community_name) values('125','4','World Trade Center');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('987','125','The Apartments Dubai World Trade Centre');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('988','125','World Trade Center');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('989','125','World Trade Centre Residence');
insert into tb_community (id,city_id, community_name) values('126','4','Zabeel');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('991','126','Zabeel 1');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('992','126','Zabeel 2');
insert into tb_subcommunity (id, community_id, subcommunity_name) values('993','126','Zabeel Road');