-- MySQL Script generated by MySQL Workbench
-- 12/01/14 18:12:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softlinecsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softlinecsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softlinecsdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `softlinecsdb` ;

-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_property_owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_property_owner` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL,
  `middle_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `gender` CHAR(10) NULL,
  `dob` DATE NULL,
  `marital_stat` CHAR(15) NULL,
  `passport_no` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NULL,
  `postalcode` VARCHAR(45) NULL,
  `postofficeboxnumber` VARCHAR(45) NULL,
  `addressRegion` VARCHAR(45) NULL,
  `addressLocality` VARCHAR(45) NULL,
  `addressCountry` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_nationality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_nationality` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `telephone_no` INT(50) NULL,
  `mobile_no` INT(50) NULL,
  `fax_no` INT(50) NULL,
  `email` VARCHAR(100) NULL,
  `property_owner_id` BIGINT(20) NULL,
  `tb_address_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `national_prop_owner_fk_idx` (`property_owner_id` ASC),
  INDEX `fk_tb_nationality_tb_address1_idx` (`tb_address_id` ASC),
  CONSTRAINT `national_prop_owner_fk`
    FOREIGN KEY (`property_owner_id`)
    REFERENCES `softlinecsdb`.`tb_property_owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_nationality_tb_address1`
    FOREIGN KEY (`tb_address_id`)
    REFERENCES `softlinecsdb`.`tb_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_propertyfinder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_propertyfinder` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL,
  `community` VARCHAR(255) NULL,
  `subcommunity` VARCHAR(255) NULL,
  `re_property` VARCHAR(255) NULL,
  `property_type` VARCHAR(45) NULL,
  `building_name` VARCHAR(100) NULL,
  `unit_number` VARCHAR(45) NULL,
  `developer_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_property_owner_has_tb_propertyfinder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_property_owner_has_tb_propertyfinder` (
  `tb_property_owner_id` BIGINT(20) NOT NULL,
  `tb_propertyfinder_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`tb_property_owner_id`, `tb_propertyfinder_id`),
  INDEX `fk_tb_property_owner_has_tb_propertyfinder_tb_propertyfinde_idx` (`tb_propertyfinder_id` ASC),
  INDEX `fk_tb_property_owner_has_tb_propertyfinder_tb_property_owne_idx` (`tb_property_owner_id` ASC),
  CONSTRAINT `fk_tb_property_owner_has_tb_propertyfinder_tb_property_owner1`
    FOREIGN KEY (`tb_property_owner_id`)
    REFERENCES `softlinecsdb`.`tb_property_owner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_property_owner_has_tb_propertyfinder_tb_propertyfinder1`
    FOREIGN KEY (`tb_propertyfinder_id`)
    REFERENCES `softlinecsdb`.`tb_propertyfinder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_residential_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_residential_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_commercial_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_commercial_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softlinecsdb`.`tb_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_city` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
