CREATE TABLE IF NOT EXISTS `tb_staff_licenses` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `staff_id` bigint(20) DEFAULT NULL,
  `dl_num` int(20) DEFAULT NULL,
  `dl_issue` date DEFAULT NULL,
  `dl_expiry` date DEFAULT NULL,
  `dl_others` varchar(100) DEFAULT NULL,
  `lc_num` int(20) DEFAULT NULL,
  `lc_issue` date DEFAULT NULL,
  `lc_expiry` date DEFAULT NULL,
  `lc_others` varchar(100) DEFAULT NULL,
  `rid_num` int(20) DEFAULT NULL,
  `rid_issue` date DEFAULT NULL,
  `rid_expiry` date DEFAULT NULL,
  `rid_others` varchar(100) DEFAULT NULL,
  `vs_num` int(20) DEFAULT NULL,
  `vs_issue` date DEFAULT NULL,
  `vs_expiry` date DEFAULT NULL,
  `vs_others` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
