CREATE TABLE IF NOT EXISTS `softlinecsdb`.`tb_country` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(100) NULL,
  PRIMARY KEY (`int`))
ENGINE = InnoDB;
insert into tb_country values('1','United Arab Emirates');
insert into tb_country values('2','Denmark');
insert into tb_country values('3','United Kingdom');
insert into tb_country values('4','United States');
insert into tb_country values('5','Germany');
insert into tb_country values('6','Saudi Arabia');
insert into tb_country values('7','India');
insert into tb_country values('8','Pakistan');
insert into tb_country values('9','Ukraine');
insert into tb_country values('10','Kuwait');
insert into tb_country values('11','South Africa');
insert into tb_country values('12','Iran');
insert into tb_country values('13','Spain');
insert into tb_country values('14','Qatar');
insert into tb_country values('15','Bahrain');
insert into tb_country values('16','Ireland');
insert into tb_country values('17','Canada');
insert into tb_country values('18','Azerbaijan');
insert into tb_country values('19','Sudan');
insert into tb_country values('20','Morocco');
insert into tb_country values('21','Botswana');
insert into tb_country values('22','Jordan');
insert into tb_country values('23','Malaysia');
insert into tb_country values('24','Singapore');
insert into tb_country values('25','Switzerland');
insert into tb_country values('26','Korea, Democratic People\'s Republic of');
insert into tb_country values('27','Italy');
insert into tb_country values('28','Kenya');
insert into tb_country values('29','Kazakhstan');
insert into tb_country values('30','Egypt');
insert into tb_country values('31','Finland');
insert into tb_country values('32','Seychelles');
insert into tb_country values('33','Japan');
insert into tb_country values('34','Indonesia');
insert into tb_country values('35','Tanzania, United Republic of');
insert into tb_country values('36','Oman');
insert into tb_country values('37','Sweden');
insert into tb_country values('38','New Zealand');
insert into tb_country values('39','Netherlands');
insert into tb_country values('40','Lebanon');
insert into tb_country values('41','Monaco');
insert into tb_country values('42','Australia');
insert into tb_country values('43','Hong Kong');
insert into tb_country values('44','Syrian Arab Republic');
insert into tb_country values('45','China');
insert into tb_country values('46','Greece');
insert into tb_country values('47','France');
insert into tb_country values('48','Turkey');
